// TRY-CATCH aprueba de errores

const num1 = 24;
const num3 = 10;


console.log(num1);

try {
    console.log(num2);
} catch (error) {
    console.log(error, 'FALLO');
}

console.log(num3);